theme = "tokyonight"
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor]
true-color = true
bufferline = "multiple"
line-number = "relative"
cursorline = true

[editor.file-picker]
hidden = false
git-ignore = true
ignore = true
